name: CI

on: [pull_request]

jobs:
  lint:
    name: SwiftLint
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: brew install swiftlint
    - name: Lint
      run: make lint

  build:
    name: MacOS Latest
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test
    - name: Run tests in parallel
      run: swift test --parallel

  ubuntu:
    name: Ubuntu Latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test
    - name: Run tests in parallel
      run: swift test --parallel
